INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (14, '6789', 'ไทวัสดุ');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (15, '1212', 'โกบอลเฮ้าส์');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (16, '12345', 'ดูโฮม');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (17, '', 'บุญถาวรไลท์ติ้ง(NNN)');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (18, '', 'BR');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (19, '', 'ศรีชลธร');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (20, '', 'คูริฮารา');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (21, '', 'ควินตัส');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (22, '', 'ไดน่า ฟลูอิด');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (23, '', 'ล็อกซเล่ย์');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (24, '', 'ล็อกซเล่ย์ เพาเวอร์');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (25, '', 'เอ็นเทค');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (26, '', 'ดับเบิ้ลอาร์');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (27, '', 'ศิรกร');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (28, '', 'วิรุฬ');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (29, '', 'เลคิเซ่');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (30, '', 'เอ็มโกลบอล ');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (31, '', 'ธงไทโชติ');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (32, '', 'เดมโก้');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (33, '', 'สิทรอน');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (34, '', 'อาร์ เอส เอส');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (35, '', 'บ. อีพีพี');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (36, '', 'ไทยนอร์ทเทอร์น');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (37, '', 'คลอลิตี้ ซินเนอร์ยี่');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (38, '', 'ซินเท็ค คอนสตรัคชั่น');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (39, '', 'วรประดิษฐ์');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (40, '', 'เนชั่นแนล เพาเวอร์ ซัพพลาย');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (41, '', 'เมกาโฮม');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (42, '', 'โฮมโปร');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (43, '', 'ไฮโวลพลัส');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (44, '', 'การไฟฟ้าส่วนภูมิภาค');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (45, '', 'การไฟฟ้านครหลวง');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (73, '', 'ชัยเจริญ');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (74, '', 'ศรีนคร');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (90, '', 'เค.เอ็นจิเนียริ่ง เพาเวอร์');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (91, '', 'อะโกรเทค เอ็นเนอร์ยี');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (92, '', 'บริษัท วินบริดจ์ จำกัด');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (93, '', 'เลี้ยวเจริญ');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (94, '', 'บิ๊กล็อต');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (95, '', 'บ.ทีโอเอสเอส');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (100, '', 'บ.อาคเนย์ทร้าฟฟิค ');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (101, '', 'บ.ธนากร');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (102, '', 'พม่า');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (103, '', 'กัมพูชา');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (104, '', 'KSท่อพีวีซี ');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (105, '', 'บริษัท อาซีฟา');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (106, '', 'เคลิงค์ แอดวานซ์');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (107, '', 'ทิมพาโน');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (108, '', 'บ. วี.ซี.เค.อินดัสเตรียล ไลน์ส');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (109, '', 'บ.ท่าอากาศยานไทย จก.');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (110, '', 'บ. เออีเอส เอ็นเนอร์จี');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (111, '', 'บ. เอ็ม โกลบอล');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (112, '', 'บ.เฟคตัม จก.');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (113, '', '็Shopee');
INSERT INTO `company`(`company_id`, `id_code`, `company_name`) VALUES (114, '', 'Lazada');
